#!/bin/bash
set -euo pipefail
IFS=$'\n\t'
function defaults() {
    PORT=3141
    u=devpi
    venv=env
    PREFIX=/
    venvbin=${PREFIX}/${venv}/bin
}

defaults

${venvbin}/devpi use http://localhost:3141 > /dev/null 2>&1
${venvbin}/devpi login root --password=$(cat "$DEVPI_SERVER_ROOT/.root_password")

if [ "${1:-}" == "bash" ]; then
    exec "$@"
fi
exec ${venvbin}/devpi "$@"
